#!/bin/sh -e
. /usr/share/debconf/confmodule

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;
    remove)
    ;;
    purge)
        if [ -f /etc/manitou-mdx.conf ]; then
          rm -f /etc/manitou-mdx.conf
        fi
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#
